# Generated by Django 3.1.5 on 2021-03-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210328_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=25)),
                ('review_msg', models.TextField()),
                ('rating', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
