# Generated by Django 3.1.5 on 2021-03-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210328_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='', upload_to='Reviewimages'),
        ),
    ]
