# Generated by Django 3.1.5 on 2021-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210330_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='', upload_to='Review/images'),
        ),
    ]
